### ISSUE TITLE
Geofill fails on Civi 5.51.1

### ISSUE THREAD

**Issue by andyburnsco** [ginkgostreet/com.ginkgostreet.geofill#10]
The geocoder has been successful up to Civi 5.50.3. I upgraded to 5.51.1, and Google is still geocoding correctly, however no address fields are being populated. This fails on both the "Fill" and "Overwrite" policy setting.

This extension worked fine with USPS standardization. However, noting that I disabled USPS standardization and therefore ruled out that being a conflict.

No log of error with report errors extension.

**Comment by twomice** [comment]
I think this is caused by a bug in civicrm core as of 5.51.0. Reference: https://lab.civicrm.org/dev/core/-/issues/3756 

PR forthcoming.

**Comment by caracolmzd** [comment]
Thanks @twomice !

**Comment by twomice** [comment]
PR submitted to core: https://github.com/civicrm/civicrm-core/pull/24067
